FROM alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add bash git curl  wget  net-tools  busybox-extras iproute2  tcpdump htop iftop strace procps sysstat vim tree nmap lsblk nethogs rsync glances && apk cache clean
